name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
          - windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Dependencies (ubuntu)
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt install meson gifsicle valgrind
      - name: Dependencies (macos)
        if: contains(matrix.os, 'macos')
        run: brew install meson gifsicle
      - name: Dependencies (windows)
        if: contains(matrix.os, 'windows')
        run: |
          choco install gifsicle
          python -m pip install pip==21.3.1
      - name: Build and test (windows)
        if: contains(matrix.os, 'windows')
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          meson-version: "0.59.0"
          ninja-version: "1.10.0.post3"
      - name: Build and test (ubuntu & macos)
        if: ${{ !contains(matrix.os, 'windows') }}
        run: meson setup build && meson test -C build
      - name: Check MD5 hashes
        if: contains(matrix.os, 'ubuntu')
        working-directory: build
        run: md5sum -c ../tests/tests.md5
        shell: bash
      - name: Verify test output
        run: for f in build/*.gif; do gifsicle --no-ignore-errors --info $f || exit 1; done
        shell: bash
      - name: Valgrind
        if: contains(matrix.os, 'ubuntu')
        run: basename -s .c tests/*.c | xargs meson test -C build --wrap "valgrind --memcheck:leak-check=full --memcheck:show-leak-kinds=definite --memcheck:error-exitcode=1"
        shell: bash
      - name: Valgrind output
        if: contains(matrix.os, 'ubuntu')
        run: cat build/meson-logs/testlog-valgrind.txt
